### PR TITLE
Do not merge | Cmake dependencies

### PR DESCRIPTION
**Pull request by KiBk**
Tobias, can you take a look at this? just run cmake and make -jN. But I run into an error when I try to compile it: 

DeSCAM/src/modelFactory/Optimizer/Optimizer.h:9:22: fatal error: CfgBlock.h: No such file or directory
#include <CfgBlock.h>

### CODE REVIEW

**Comment by ludwig247** [comment]
I'll take a look!

**Comment by ludwig247** [comment]
I don't get to that point: I have trouble installing Z3. 
I get the following error message. What I did:
mkdir build & cd build & make -jN 

        cp: cannot stat '/import/home/ludwig/DeSCAM/build/3rdparty/z3/install/lib64/.': No such file or directory
        CMakeFiles/Z3.dir/build.make:73: recipe for target 'Z3-prefix/src/Z3-stamp/Z3-install' failed
        make[2]: *** [Z3-prefix/src/Z3-stamp/Z3-install] Error 1
        CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Z3.dir/all' failed
        make[1]: *** [CMakeFiles/Z3.dir/all] Error 2

This could be answer to the problem: 
https://stackoverflow.com/questions/49626164/make-install-installs-libraries-in-usr-lib-instead-of-usr-lib64

**Comment by KiBk** [comment]
Oh yes, for sure, I fixed it in the last commit, I will create another pull request

**Comment by KiBk** [comment]
> I don't get to that point: I have trouble installing Z3.
> I get the following error message. What I did:
> mkdir build & cd build & make -jN
> 
> ```
>     cp: cannot stat '/import/home/ludwig/DeSCAM/build/3rdparty/z3/install/lib64/.': No such file or directory
>     CMakeFiles/Z3.dir/build.make:73: recipe for target 'Z3-prefix/src/Z3-stamp/Z3-install' failed
>     make[2]: *** [Z3-prefix/src/Z3-stamp/Z3-install] Error 1
>     CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Z3.dir/all' failed
>     make[1]: *** [CMakeFiles/Z3.dir/all] Error 2
> ```
> 
> This could be answer to the problem:
> https://stackoverflow.com/questions/49626164/make-install-installs-libraries-in-usr-lib-instead-of-usr-lib64

There is a command that copies compiled library to the place where DeSCAM sources them, it looks like you don't have lib64, inside build/3rdparty/z3/install/. Can you take a look there please?

**Comment by ludwig247** [comment]
> 
> There is a command that copies compiled library to the place where DeSCAM sources them, it looks like you don't have lib64, inside build/3rdparty/z3/install/. Can you take a look there please?

Yes the folder is called just lib. I'm running Ubuntu 16.04 LTS. 
I think the link I posted could fix this issue, if you specify a specific libdir ... other it's sometimes lib64 and somtimes lib64

Regarding the original problem. Make sure you use the following include direcotries: 

        include_directories(${CMAKE_SOURCE_DIR}/include)
        include_directories(${CMAKE_SOURCE_DIR}/example/Interfaces)
        include_directories(${CMAKE_SOURCE_DIR}/src/plugin)
        include_directories(${CMAKE_SOURCE_DIR}/src/ParseAML)
        include_directories(${CMAKE_SOURCE_DIR}/src/global/)
        include_directories(${CMAKE_SOURCE_DIR}/src/operationFactory/)
        include_directories(${CMAKE_SOURCE_DIR}/src/cfgFactory/)
        include_directories(${CMAKE_SOURCE_DIR}/src/functionFactory/)
        include_directories(${CMAKE_SOURCE_DIR}/src/propertyFactory/)
        include_directories(${CMAKE_SOURCE_DIR}/src/propertyFactory/operationGraph)#do include this directory? its files already included in propertyFactory library
        include_directories(${CMAKE_SOURCE_DIR}/src/propertySuite/)
        include_directories(${CMAKE_SOURCE_DIR}/src/model/)
        include_directories(${CMAKE_SOURCE_DIR}/src/model/Stmts)#do include this directory? its files already included in model library
        include_directories(${CMAKE_SOURCE_DIR}/src/modelFactory)
        include_directories(${CMAKE_SOURCE_DIR}/src/modelFactory/CFG)#why include this directory?
        include_directories(${CMAKE_SOURCE_DIR}/src/modelFactory/CFG/new)#why include this directory?
        include_directories(${CMAKE_SOURCE_DIR}/tests/)

**Comment by ludwig247** [comment]
Any news?

**Pull request closed without merging**
