### PR TITLE
-Added folder RISCV_isa_array in the example folder.

### PR DESCRIPTION
**Pull request by luisalrivas77**
-Added implementation of a RISCV ISA with the register file implemented as an array in the RISCV_isa_array/ESL folder. The file containing
 the implementation is the file ISA_array.h
-Added implementattion of the RTL design in SystemVerilog of the mentioned RISCV ISA in the RISCV_isa_array/RTL/RISCV_isa_array_RTL folder with its SVA properties,

### CODE REVIEW

**Review by ludwig247 — CHANGES_REQUESTED** [review]
Please don't commit your build files (cmake-build-debug)  ... please add a Readme.md explaining what is what.

**Comment by luisalrivas77** [comment]
Should I also remove the CMakeFiles directory?

**Comment by luisalrivas77** [comment]
I think I finally managed to remove the cmake-build-debug folder. Let me know if there is anything else I should do

**Comment by ludwig247** [comment]
> I think I finally managed to remove the cmake-build-debug folder. Let me know if there is anything else I should do

There is still some CMake files in the folder. Please make sure your remove them. 
Always be really careful what you add to versioning. It's really hard (sometimes impossible) to remove files from versioning once they are in there.  If I would checkout a previous commit I would find the files. 

Versioning files takes time. If you use the command line, never ever use git add -A  ... always add files step-by-step. 
If you use an IDE really check with each commit if you have any files part of the commit that shouldn't be.

**Comment by luisalrivas77** [comment]
> There is still some CMake files in the folder. Please make sure your remove them.
> Always be really careful what you add to versioning. It's really hard (sometimes impossible) to remove files from versioning once they are in there. If I would checkout a previous commit I would find the files.
> 
> Versioning files takes time. If you use the command line, never ever use git add -A ... always add files step-by-step.
> If you use an IDE really check with each commit if you have any files part of the commit that shouldn't be.

Ok thank you for the tip. I will be more careful when versioning files. I removed the remaining CMake files

**Comment by ludwig247** [comment]
Let me know. once it's done then I'll add to the versioning

**Review by ludwig247 — APPROVED** [review]

**Pull request merged**
